  CREATE TABLE "FASHION_PRODUCTS" 
   (	"PRODUCT_ID" NUMBER, 
	"IMAGE_NAME" VARCHAR2(500), 
	"DISPLAY_NAME" VARCHAR2(1000), 
	"CATEGORY" VARCHAR2(500), 
	"DESCRIPTION" CLOB, 
	"IMAGE_BLOB" BLOB,
	"IMAGE_EMBEDDING" VECTOR, 
	"DESC_EMBEDDING" VECTOR, 
	"STOCK_QUANTITY" NUMBER
	CONSTRAINT FASHION_PRODUCTS_PK PRIMARY KEY (PRODUCT_ID)
   ) 
   LOB (DESCRIPTION) STORE AS SECUREFILE
   LOB (IMAGE_BLOB)  STORE AS SECUREFILE;