CREATE TABLE "FASHION_SELECTED_IMAGE" 
   (	"SESSION_ID" VARCHAR2(100), 
	"PRODUCT_ID" NUMBER, 
	"IMAGE_BLOB" BLOB, 
	"IMAGE_EMBEDDING" VECTOR, 
	"SELECTED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"SELECTED_CATEGORY" VARCHAR2(500), 
	 CONSTRAINT "FASHION_SELECTED_PK" PRIMARY KEY ("SESSION_ID")
  USING INDEX  ENABLE
   ) ;